# Generated by Django 2.2.4 on 2019-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='able',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='max',
            field=models.IntegerField(default=4),
        ),
    ]
