# Generated by Django 2.2.4 on 2019-11-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20191110_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(default='??번 테이블', max_length=15),
        ),
    ]
