# Generated by Django 2.2.6 on 2019-10-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('localInfo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idName', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('nickName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('normaluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.NormalUser')),
                ('phoneNumber', models.CharField(max_length=12)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Location')),
            ],
            bases=('login.normaluser',),
        ),
    ]
