# Generated by Django 2.2.6 on 2019-10-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('normaluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.NormalUser')),
                ('restaurantNumber', models.CharField(max_length=12)),
                ('managerPhone', models.CharField(max_length=12)),
            ],
            bases=('login.normaluser',),
        ),
        migrations.RemoveField(
            model_name='location',
            name='localInfo',
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Location'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Location')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ManagerUser')),
            ],
        ),
    ]
