# Generated by Django 2.2.6 on 2019-10-29 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191029_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='manager',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ManagerUser',
        ),
    ]
