# Generated by Django 2.2.4 on 2019-11-10 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191029_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(default='없음!', on_delete=django.db.models.deletion.DO_NOTHING, to='login.Location'),
        ),
    ]
