# Generated by Django 2.2.6 on 2019-11-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_customer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
