# Generated by Django 2.2.4 on 2019-11-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191113_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isBlack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isVip',
            field=models.BooleanField(default=False),
        ),
    ]
