# Generated by Django 2.2.4 on 2019-11-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
