# Generated by Django 2.2.6 on 2019-10-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('reservation_time', models.DateTimeField()),
                ('people', models.IntegerField()),
                ('acceptOn', models.BooleanField(default=False)),
            ],
        ),
    ]
