# Generated by Django 2.2.6 on 2019-11-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0005_food_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='acceptOn',
        ),
    ]
