# Generated by Django 2.2.6 on 2019-11-18 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191113_2041'),
        ('reserv', '0006_remove_reservation_accepton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relate_reserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserv.Reservation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
    ]
