# Generated by Django 2.2.4 on 2019-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0007_relate_reserv'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='isCheck',
            field=models.BooleanField(default=False),
        ),
    ]
